Shader "BSK/Rendering/CustomLightingCalculation"
{
    SubShader
    {
        Tags
        {
            "RenderPipeline" = "UniversalPipeline"
            // RenderType: <None>
            // Queue: <None>
            // DisableBatching: <None>
            "ShaderGraphShader" = "true"
            "ShaderGraphTargetId" = "UniversalFullscreenSubTarget"
        }
        Pass
        {
            Name "Blit"

            // Render State
            Cull Off
            Blend Off
            ZTest Off
            ZWrite Off

            // Debug
            // <None>

            // -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
            // Pass

            HLSLPROGRAM

            // Pragmas
            #define MAX_ARRAY_SIZE 20

            #pragma target 3.0
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile __ POINT_LIGHT_TEXTURE

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            float _MaxPointLightDistance;

            float _PointLightCount;
            float4 _PointLightPositions [MAX_ARRAY_SIZE];
            float4 _PointLightColors [MAX_ARRAY_SIZE];
            float _PointLightRange [MAX_ARRAY_SIZE];
            float3 _CameraPosition;

            struct Attributes
            {
                // The positionOS variable contains the vertex positions in object
                // space.
                float4 positionOS : POSITION;
            };

            struct Varyings
            {
                float4 positionHCS : SV_POSITION;
                float2 uv : TEXCOORD0;
            };

            // Fullscreen triangle generated by SV_VertexID
            Varyings vert(uint vid : SV_VertexID)
            {
                Varyings OUT;

                // Build fullscreen triangle positions / uvs (common pattern)
                float2 pos;
                pos.x = ( (vid << 1) & 2 ); // 0,2,0  -> maps to 0,2,0
                pos.y = (vid & 2); // 0, 0, 2 -> maps to 0, 0, 2

                // Convert to NDC (- 1..1)
                float2 ndc = pos * 2.0 - 1.0;
                OUT.positionHCS = float4(ndc, 0.0, 1.0);
                OUT.uv = pos;

                return OUT;
            }

            // The fragment shader definition.
            float4 frag(Varyings IN) : SV_Target
            {
                float3 color = float3(0, 0, 0);

                #if defined(POINT_LIGHT_TEXTURE)

                float3 pixelWP = float3(0, 0, 0);

                pixelWP.x = lerp(_MaxPointLightDistance, - _MaxPointLightDistance, IN.uv.x);
                #if UNITY_UV_STARTS_AT_TOP
                pixelWP.z = lerp(_MaxPointLightDistance, - _MaxPointLightDistance, IN.uv.y);
                #else
                pixelWP.z = lerp(_MaxPointLightDistance, - _MaxPointLightDistance, 1 - IN.uv.y);
                #endif


                for (int i = 0; i < _PointLightCount && i < MAX_ARRAY_SIZE; i ++)
                {
                    // Light world position
                    float3 lightPos = _PointLightPositions[i];
                    lightPos.y = 0;

                    float range = _PointLightRange[i];
                    float intensity = _PointLightPositions[i].w; // stored intensity

                    // Vector from pixel → light
                    float3 camPos = _CameraPosition;
                    camPos.y = 0;
                    float3 cameraOffset = lightPos - camPos;
                    cameraOffset.y = 0;
                    float3 toLight = cameraOffset - pixelWP;

                    float d = length(toLight);
                    if (d > range)
                    continue;

                    // Smooth falloff 1.0 → 0.0 over distance
                    float t = smoothstep(range, 0.0, d);
                    float lightValue = t * intensity; // quadratic smoother curve
                    float3 lightColor = _PointLightColors[i];
                    lightColor *= lightValue;
                    color += lightColor; // add white light
                }
                #endif
                return float4(color, 1);

            }
            ENDHLSL
        }
    }
}
