Shader "BSK/Rendering/TransperancyBlitShader"
{
    Properties
    {
        _BaseMap ("Base Map", 2D) = "white" {}
    }
    SubShader
    {
        Tags
        {
            "RenderPipeline" = "UniversalPipeline"
            "ShaderGraphShader" = "true"
            "ShaderGraphTargetId" = "UniversalFullscreenSubTarget"
        }
        Pass
        {
            Name "Blit"

            // Render State
            Cull Off
            Blend Off
            ZTest Off
            ZWrite Off

            // Debug
            // <None>

            // -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
            // Pass

            HLSLPROGRAM

            #pragma target 3.0
            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"


            struct VertexAttr
            {
                // The positionOS variable contains the vertex positions in object
                // space.
                float4 positionOS : POSITION;
            };

            struct FragAttr
            {
                float4 positionHCS : SV_POSITION;
                float2 uv : TEXCOORD0;
            };


            // FRAMEBUFFER_INPUT_X_FLOAT(0); // Declares the input attachment at index 0
            TEXTURE2D(_BaseMap);
            SAMPLER(SamplerState_Linear_Repeat);

            // Fullscreen triangle generated by SV_VertexID
            FragAttr vert(uint vid : SV_VertexID)
            {
                FragAttr OUT;

                // Build fullscreen triangle positions / uvs (common pattern)
                float2 pos;
                pos.x = ( (vid << 1) & 2 ); // 0,2,0  -> maps to 0,2,0
                pos.y = (vid & 2); // 0, 0, 2 -> maps to 0, 0, 2

                // Convert to NDC (- 1..1)
                float2 ndc = pos * 2.0 - 1.0;
                OUT.positionHCS = float4(ndc, 0.0, 1.0);
                OUT.uv = pos;

                return OUT;
            }

            // The fragment shader definition.
            float4 frag(FragAttr IN) : SV_Target
            {
                #if UNITY_UV_STARTS_AT_TOP
                IN.uv.y = 1 - IN.uv.y;
                #endif

                // half4 currentColor = LOAD_FRAMEBUFFER_X_INPUT(0, IN.uv);
                half4 currentColor = _BaseMap.Sample(SamplerState_Linear_Repeat, IN.uv);;
                return currentColor;
            }
            ENDHLSL
        }
    }
}
